version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hubspot-sync-postgres
    environment:
      POSTGRES_USER: hubspot_user
      POSTGRES_PASSWORD: hubspot_password
      POSTGRES_DB: hubspot_sync
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hubspot-network

  redis:
    image: redis:7-alpine
    container_name: hubspot-sync-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - hubspot-network

  # Uncomment to run the app in Docker
  # app:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.dev
  #   container_name: hubspot-sync-app
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     DATABASE_URL: postgresql://hubspot_user:hubspot_password@postgres:5432/hubspot_sync
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #   depends_on:
  #     - postgres
  #     - redis
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   networks:
  #     - hubspot-network
  #   command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  hubspot-network:
    driver: bridge